"""add credits table

Revision ID: df81974f16c9
Revises: 0001_initial
Create Date: 2026-05-22 19:12:08.737047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df81974f16c9'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_profiles',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('credits_balance', sa.Float(), nullable=False),
    sa.Column('auto_recharge_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('marketing_assets', 'marketing_angle',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('marketing_assets', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('marketing_assets', 'created_at',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('sessions', 'updated_at',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('voice_profiles', 'updated_at',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_profiles', 'updated_at',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('sessions', 'updated_at',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('marketing_assets', 'created_at',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('marketing_assets', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('marketing_assets', 'marketing_angle',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('credit_profiles')
    # ### end Alembic commands ###
